server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Support client-side routing by rewriting 404s to index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
