apiVersion: v1
kind: Service
metadata:
  name: freightsimple-ai
  labels:
    app: freightsimple-ai
spec:
  type: LoadBalancer
  selector:
    app: freightsimple-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
